### ISSUE TITLE
不显示结果

### ISSUE THREAD

**Issue by Bai-Zane** [love98ooo/ZhengFangJiaoWuSystemTampermonkeyScript#18]
['2023-2024,1,JS170101S,Python程序设计（混合式）,限选,&nbsp\;,2,&nbsp\;,  3.70,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,87,0,&nbsp\;,&nbsp\;,&nbsp\;,计算机学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,GL1002T0C,创新与创业管理B（在线）,限选,&nbsp\;,2,&nbsp\;,  3.30,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,83,0,&nbsp\;,&nbsp\;,&nbsp\;,管理学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,LX1042F6S,大学物理（下）,必修,&nbsp\;,3,&nbsp\;,  4.10,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,91,0,&nbsp\;,&nbsp\;,&nbsp\;,理学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,DG1005X7S,电路分析基础C,必修,&nbsp\;,2.0,&nbsp\;,  4.70,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,97,0,&nbsp\;,&nbsp\;,&nbsp\;,电子与光学工程学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,GC1003X0C,金工实习,必修,&nbsp\;,1,&nbsp\;,  4.50,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,优秀,0,&nbsp\;,&nbsp\;,&nbsp\;,工程实验教学部,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,MY1001T0S,马克思主义基本原理,必修,&nbsp\;,3,&nbsp\;,  4.50,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,95,0,&nbsp\;,&nbsp\;,&nbsp\;,马克思主义学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,JS140201S,数据结构（混合式）,必修,&nbsp\;,3.5,&nbsp\;,  4.30,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,93,0,&nbsp\;,&nbsp\;,&nbsp\;,计算机学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,LX1034F6C,数学实验B,必修,&nbsp\;,1,&nbsp\;,  3.50,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,良好,0,&nbsp\;,&nbsp\;,&nbsp\;,理学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,TY0003T0C,体育III,必修,&nbsp\;,1,&nbsp\;,  3.30,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,83,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,体育部,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,DSXA03T0C,文艺作品中的城市意象,任选,全校任选课,1,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,97,0,&nbsp\;,&nbsp\;,&nbsp\;,社会与人口学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,LX1048F4S,物理实验（下）,必修,&nbsp\;,1,&nbsp\;,  3.60,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,86,0,&nbsp\;,&nbsp\;,&nbsp\;,理学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,MY1007T0C,形势与政策III,必修,&nbsp\;,0,&nbsp\;,  3.50,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,良好,0,&nbsp\;,&nbsp\;,&nbsp\;,马克思主义学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,SR1003T0C,应用文写作,必修,&nbsp\;,1,&nbsp\;,  4.30,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,93,0,&nbsp\;,&nbsp\;,&nbsp\;,社会与人口学院,&nbsp\;,0,&nbsp\;,0,1,2,3', '2023-2024,1,WY151300S,综合英语Ⅰ-D（高阶上）,必修,&nbsp\;,2,&nbsp\;,  3.20,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,82,0,&nbsp\;,&nbsp\;,&nbsp\;,外国语学院,&nbsp\;,0,&nbsp\;,Visible,f,;;;;;;;;;,0', '01,必修,0,18.50,0,0,0,0,1,2,3,4,5,6,02,限选,0,4,0,0,0,0,1,2,3,4,5,6,04,任选,0', '1,0,0,0,0,1,2,3,4,5,6,05,辅修,0,0,0,0,0,0,1,2,3,4,5,6,99,b\,/b\,0,23.50,0', '0,;;;;;;;;;,0,1,PageCount_!ItemCount;_!DataSourceItemCount;DataKeys;,1,3,3,,0,1,2,3,0,1,2,3,4,全校任选课,0,1,0,0,0,1,2,3,4,在线开放课程,0,0,0,0,0,1,2,3', 'b\,/b\,0,1,0,0,;;;;;;;;;,0,0,PageCount_!ItemCount;_!DataSourceItemCount;DataKeys;,1,1,1,,Visible,f,0,1,0,1,2,3,4,5,6,合计,&nbsp\;,&nbsp\;,&nbsp\;,&nbsp\;,次,&nbsp\;,0,1,0,VisiblePageCount;_!ItemCount;_!DataSourceItemCount;DataKeys;']

**Comment by love98ooo** [comment]
#16
