### ISSUE TITLE
对校外的访问者无法查看成绩

### ISSUE THREAD

**Issue by MaxtuneLee** [love98ooo/ZhengFangJiaoWuSystemTampermonkeyScript#6]
由于校外通过webvpn访问教务系统，url为vpn.njupt.edu.cn开头，插件无法识别，导致插件没生效

**Comment by love98ooo** [comment]
经过测试，插件可以识别，插件失效原因在校外访问时，iframeautoheight元素中所需要的参数为“null”，所以无法正常添加入口button。目前正在尝试解决……

**Comment by love98ooo** [comment]
在v0.3.3中已经修复
